[tool.poetry]
package-mode = false
name = "backend"
version = "0.1.0"
description = ""
authors = ["leocodeio <basicleo@787>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyaudio = "^0.2.14"
speechrecognition = "^3.10.4"
setuptools = "^74.1.1"
flask = "^3.0.3"
google-cloud-speech = "^2.27.0"
nltk = "^3.9.1"
librosa = "^0.10.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
